services:
    db:
        image: postgres
        restart: always
        ports:
            - 5432:5432
        shm_size: 128mb
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: hc
        networks:
            - hc_network

networks:
    hc_network:
        external: true
