services:
    homecontroller_dev:
        build: "."
        volumes:
            - "../..:/app"
            - "/var/run/docker.sock:/var/run/docker.sock"
        container_name: "homecontroller_dev"
        networks:
            - hc_network

networks:
    hc_network:
        external: true
