services:
    homecontroller_dev:
        build: "."
        volumes:
            - "../..:/app"
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "/run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.sock"
        environment:
            SSH_AUTH_SOCK: "/run/host-services/ssh-auth.sock"
        container_name: "homecontroller_dev"
        networks:
            - hc_network

networks:
    hc_network:
        external: true
